version: "3.8"
services:
  rabbit-mq:
    image: rabbitmq:alpine
    hostname: "rabbit"
    ports:
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_VHOST=1
      - RABBITMQ_CONFIG_FILE=/etc/rabbitmq/rabbitmq
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    restart: on-failure

  redis:
    image: redis:alpine
    hostname: "redis"
    ports:
      - "6379:6379"
    restart: on-failure

  application:
    &application
    build:
      context: .
    command: ["python", "main.py"]
    depends_on:
      - rabbit-mq
      - redis
    volumes:
      - .:/app
    restart: on-failure

  celery_worker:
    <<: *application
    depends_on:
      - rabbit-mq
    user: developer
    command: ["celery", "-A", "scrapper", "worker", "-l", "INFO"]
    restart: on-failure
